version: '3.3'
services:
  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
    environment:
      - ADVERTISED_HOST=localhost
  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - docker_elk
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  kibana:
    image: kibana:5.6
    ports:
      - "5601:5601"
    networks:
      - docker_elk
volumes:
  esdata1:
    driver: local

networks:
  docker_elk:
    driver: bridge